Controllers/OrganizationAdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OneDirect.Helper;
using OneDirect.Repository.Interface;
using OneDirect.Models;
using Microsoft.Extensions.Logging;
using OneDirect.Repository;
using Microsoft.AspNetCore.Mvc.Rendering;
using OneDirect.ViewModels;
using OneDirect.Extensions;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace OneDirect.Controllers
{
    [TypeFilter(typeof(LoginAuthorizeAttribute))]
    public class OrganizationAdministratorController : Controller
    {
        private readonly IUserInterface lIUserRepository;
        private readonly IProtocolInterface lIProtocolInterface;
        private readonly IPatientRxInterface lIPatientRxRepository;
        private readonly ILogger logger;
        private OneDirectContext context;

        public OrganizationAdministratorController(OneDirectContext context, ILogger<OrganizationAdministratorController> plogger, IPatientRxInterface IPatientRxRepository)
        {
            logger = plogger;
            this.context = context;
            lIUserRepository = new UserRepository(context);
            lIProtocolInterface = new ProtocolRepository(context);
            lIPatientRxRepository = IPatientRxRepository;
        }


        //give the list of organization administrators
        // GET: /<controller>/
        public IActionResult Index()
        {
            var response = new Dictionary<string, object>();
            List<User> pUser = new List<User>();
            try
            {
                logger.LogDebug("Installer Start");

                pUser = lIUserRepository.getUserListByType(ConstantsVar.Admin);
                if (pUser != null && pUser.Count > 0)
                {
                    pUser = pUser.Where(x => x.UserId != "admin").ToList();
                }
                ViewBag.userlist = pUser;
                return View();
            }
            catch (Exception ex)
            {
                logger.LogDebug("Installer Error: " + ex);
                return null;
            }

        }
        public IActionResult Add()
        {
           
            return View();
        }

        // add new record for organization administrator with unique npi and UserId
        [HttpPost]
        public IActionResult Add(UserViewModel pUser)
        {
            pUser.Type = ConstantsVar.Admin;
            User _user = lIUserRepository.getUser(pUser.UserId);
            User _user2 = lIUserRepository.getUserNpi(pUser.Npi);
            User _userNew = UserExtension.UserViewModelToUser(pUser);
            if ((_user == null) && (_user2 == null))
            {
                _userNew.Phone = RemoveSpecialChars(_userNew.Phone);
                string _User = lIUserRepository.InsertUser(_userNew);
                if (_User == "Username already exists")
                {
                    TempData["Admin"] = JsonConvert.SerializeObject(_userNew);
                    TempData["msg"] = "<script>Helpers.ShowMessage('User with same Organization Administrator Id is already registered, please use different one', 1);</script>";
                    pUser.UserId = null;
                    return View(pUser);
                }
            }
            else
            {
                if (_user2 != null)
                {
                    if (_user2.Npi == _userNew.Npi)
                    {
                        TempData["Admin"] = JsonConvert.SerializeObject(_userNew);
                        TempData["msg"] = "<script>Helpers.ShowMessage('User with same Npi is already registered, please use different one', 1);</script>";
                        pUser.Npi = null;
                        return View(pUser);
                    }
                }
                if (_user.UserId == _userNew.UserId)
                {
                    TempData["Admin"] = JsonConvert.SerializeObject(_userNew);
                    TempData["msg"] = "<script>Helpers.ShowMessage('User with same Organization Administrator Id is already registered, please use different one', 1);</script>";
                    pUser.UserId = null;
                    return View(pUser);
                }
            }
            return RedirectToAction("Index");
        }

        //get and show the profile of organization administrator
        public IActionResult Profile(string id)
        {
            User pUser = lIUserRepository.getUser(id);

            
            if (pUser != null)
            {
                UserViewModel _user = UserExtension.UserToUserViewModel(pUser);
                ViewBag.Name = _user.Name;
                return View(_user);
            }
            else
            {
                return View(null);
            }
        }

        //updating the changes in profile of organization administrator
        [HttpPost]
        public IActionResult Profile(UserViewModel pUser)
        {
            pUser.Type = ConstantsVar.Admin;
            if (pUser != null && !string.IsNullOrEmpty(pUser.UserId))
            {
                User luser = lIUserRepository.getUser(pUser.UserId);
                if (luser != null && luser.Npi != pUser.Npi)
                {

                    User _user2 = lIUserRepository.getUserNpi(pUser.Npi);
                    if (_user2 != null)
                    {

                        TempData["Installer"] = JsonConvert.SerializeObject(UserExtension.UserViewModelToUser(pUser));
                        TempData["msg"] = "<script>Helpers.ShowMessage('User with same Npi is already registered, please use different one', 1);</script>";
                        pUser.Npi = null;
                        return View(pUser);

                    }
                    else
                    {
                        User _user = UserExtension.UserViewModelToUser(pUser);
                        _user.Phone = RemoveSpecialChars(_user.Phone);
                        string _result = lIUserRepository.UpdateUser(_user);
                    }
                }
                else
                {
                    User _user = UserExtension.UserViewModelToUser(pUser);
                    _user.Phone = RemoveSpecialChars(_user.Phone);
                    string _result = lIUserRepository.UpdateUser(_user);
                }
            }
            if (HttpContext.Session.GetString("UserType") != null && HttpContext.Session.GetString("UserType").ToString() == ConstantsVar.Admin.ToString())
            {
                return RedirectToAction("Profile", new { id = pUser.UserId });
            }
            return RedirectToAction("Index");
        }

        //remove all the special characters from phone number before saving in database
        public string RemoveSpecialChars(string str)
        {
            string[] chars = new string[] { "-", " ", "/", "!", "@", "#", "$", "%", "^", "&", "*", "'", "\"", ";", "_", "(", ")", ":", "|", "[", "]" };
            for (var i = 0; i < chars.Length; i++)
            {
                if (str.Contains(chars[i]))
                {
                    str = str.Replace(chars[i], "");
                }
            }
            return str;
        }

        //delete the record of organization administrator
        public IActionResult Delete(string id)
        {
            User pUser = lIUserRepository.getUser(id);
            if (pUser != null)
            {
                lIUserRepository.deleteUser(pUser);

            }
            return RedirectToAction("Index");
        }

    }
}

Views/OrganizationAdministrator/Add.cshtml
@{

}
@model OneDirect.ViewModels.UserViewModel
<section class="content-header">
    <h1>
        Add Organization Administrator
       
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Patient"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Organization Administrators</li>
    </ol>
</section>

<!-- Main content -->


@using (Html.BeginForm())
{
    <div class="col-md-12" style="padding-top:20px">
        <!-- Horizontal Form -->
        <div class="box box-info">
            
            <!-- /.box-header -->
            <!-- form start -->

            <div class="box-body" style="font-size:small">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Organization Administrator Name</label>

                        <div>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                    </div>
                </div>
               
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Organization Administrator Id</label>
                        <div>
                            @Html.TextBoxFor(model => model.UserId, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserId)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="control-label">Password</label>
                        <div>
                            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Password)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">E-mail ID</label>

                        <div>
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Phone</label>

                        <div>
                            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Phone)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Address</label>

                        <div>
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Address)

                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">NPI</label>
                        <div>
                            @Html.TextBoxFor(model => model.Npi, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Npi)

                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-success pull-right" style="margin-left:10px;">Submit</button>
                <a href="@Url.Action("Index","PatientAdministrator")" class="btn btn-warning pull-right">Cancel</a>

            </div>
            <!-- /.box-footer -->

        </div>
    </div>
}

@section Scripts {
    <script src="~/Scripts/inputmask.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.input-validation-error').on('focus', function () {
                $(this).parents('.form-group').removeClass('has-error');
                $(this).attr('class', 'form-control');
                $(this).next('span.field-validation-error').attr('class', 'field-validation-valid').html('');
            })
            var input = $('#Phone');
            input.focus();
            var tmpStr = input.val();
            input.val('');
            input.val(tmpStr);
            $("button[type=submit]").click(function (e) {
                if ($('form').valid() == false) {
                    $('.field-validation-error').addClass('text-danger');
                }
            });
            $('input[name=Phone]').mask("(999) 999-9999")
        });
    </script>
}

Views/OrganizationAdministrator/Index.cshtml
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Http
@using OneDirect.Helper;
@{

}
<section class="content-header">
    <h1>
        Organization Administrators
       
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Patient"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Organization Administrators</li>
    </ol>
</section>

<!-- Main content -->


<div class="col-md-2" style="padding-top:20px">
    <table class="table table-bordered text-center">
        <td>
            <a href="/OrganizationAdministrator/Add">
                <button type="button" class="btn btn-block btn-warning btn-sm">Add</button>
            </a>
        </td>
    </table>
</div>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
              
                <!-- /.box-header -->
                <div class="box-body">
                    <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12" style="overflow-x:auto">
                                <table id="example1" class="table table-bordered table-striped dataTable" style="font-size:small" role="grid" aria-describedby="example1_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Installer Name: activate to sort column descending" style="width: 182px;">Org Administrator Name</th>
                                           
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Email: activate to sort column descending" style="width: 182px;">Email</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Installer Id: activate to sort column descending" style="width: 182px;">Org Administrator Id</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="NPI: activate to sort column descending" style="width: 182px;">NPI</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Phone: activate to sort column descending" style="width: 182px;">Phone</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Address: activate to sort column descending" style="width: 182px;">Address</th>
                                            <th tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Actions : activate to sort column descending" style="width: 182px;"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (ViewBag.userlist != null)
                                        {
                                            @foreach (var item in ViewBag.userlist)
                                            {
                                                <tr>

                                                    <td>@item.Name</td>
                                                    <td>@item.Email</td>
                                                    <td>@item.UserId</td>
                                                    <td>@item.Npi</td>
                                                    <td>
                                                        <script type="text/javascript">
                                                           s = formatPhoneNumber('@item.Phone');
                                                           function formatPhoneNumber(s) {
                                                            var s2 = (""+s).replace(/\D/g,'');
                                                            var m = s2.match(/^(\d{3})(\d{3})(\d{4})$/);
                                                            return (!m) ? "" : "(" + m[1] + ") " + m[2] + "-" + m[3];
                                                            }
                                                           document.writeln(formatPhoneNumber(s));
                                                        </script>
                                                    </td>
                                                                                         
                                                    <td>
                                                        @item.Address

                                                    </td>
                                                    <td>
                                                        @Html.ActionLink("Edit", "Profile", new { id = item.UserId }, new { @class = "label label-primary" })
                                                        
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="~/plugins/jQuery/jquery-2.2.3.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#example1').DataTable({
            "stateSave": true,
            "stateDuration": -1,
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': [-1] /* 1st one, start by the right */
            }]
        });

    });

</script>

Views/OrganizationAdministrator/Profile.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Http
@using OneDirect.Helper

@{
}
@model OneDirect.ViewModels.UserViewModel
<section class="content-header">
    <h1>
        @if (ViewBag.Name != null)
        {
            <span>@ViewBag.Name's Details </span>
        }
        else
        {
            <span>Organization Administrators</span>
        }

    </h1>
    @*kajal*@
    @if (Context.Session.GetString("UserType") == ConstantsVar.Admin.ToString())
    {
        <ol class="breadcrumb">
            <li><a href="~/Patient"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Patients</li>
        </ol>

    }
    else
    {
        <ol class="breadcrumb">
            <li><a href="~/Patient"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Organization Administrators</li>
        </ol>

    }
   
</section>

<!-- Main content -->




<div class="col-md-12" style="padding-top:20px">
    <!-- Horizontal Form -->
    <div class="box box-info">

        <!-- /.box-header -->
        <!-- form start -->
        @using (Html.BeginForm())
        {
            <div class="box-body" style="font-size:small">

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Name</label>

                        <div>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name)
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="control-label">Org Administrator id</label>
                        <div>
                            @Html.TextBoxFor(model => model.UserId, new { @class = "form-control", @readonly = true })
                            @Html.ValidationMessageFor(model => model.UserId)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputPassword3" class="control-label">Password</label>
                        <div>
                            @Html.TextBoxFor(model => model.Password, new { @class = "form-control", @type = "password" })
                            @Html.ValidationMessageFor(model => model.Password)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">E-mail ID</label>
                        <div>
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Phone</label>
                        <div>
                            @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Phone)
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">Address</label>

                        <div>
                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Address)

                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="inputEmail3" class="control-label">NPI</label>
                        <div>
                            
                            @if (!string.IsNullOrEmpty(Model.Npi))
                            {
                                @Html.TextBoxFor(model => model.Npi, new { @class = "form-control", @readonly = true })
                            }
                            else
                            {
                                @Html.TextBoxFor(model => model.Npi, new { @class = "form-control" })

                            }
                            @Html.ValidationMessageFor(model => model.Npi)

                        </div>
                    </div>
                </div>

            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                @if (@Context.Session.GetString("UserType") != "3")
                {
                    <button type="submit" class="btn btn-success pull-right" style="margin-left:10px;">Submit</button>
                }
                @if (@Context.Session.GetString("UserType") != "2")
                {
                    <a href="@Url.Action("Index","OrganizationAdministrator")" class="btn btn-warning pull-right">Cancel</a>
                }

            </div>
            <!-- /.box-footer -->
        }
    </div>
</div>
@section Scripts {
    <script src="~/Scripts/inputmask.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.input-validation-error').on('focus', function () {
                $(this).parents('.form-group').removeClass('has-error');
                $(this).attr('class', 'form-control');
                $(this).next('span.field-validation-error').attr('class', 'field-validation-valid').html('');
            })
            var input = $('#Phone');
            input.focus();
            var tmpStr = input.val();
            input.val('');
            input.val(tmpStr);
            $("button[type=submit]").click(function (e) {
                if ($('form').valid() == false) {
                    $('.field-validation-error').addClass('text-danger');
                }
            });
            $('input[name=Phone]').on('keyup', function (e) {
            });
            $('input[name=Phone]').mask("(999) 999-9999")



        });

    </script>
}